# Generated by Django 2.2 on 2020-05-12 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='library_videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='')),
                ('youtube_url', models.CharField(max_length=250)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.library')),
            ],
            options={
                'verbose_name_plural': 'Library Videos',
            },
        ),
        migrations.CreateModel(
            name='library_ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField()),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.library')),
            ],
        ),
        migrations.CreateModel(
            name='library_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.library')),
            ],
            options={
                'verbose_name_plural': 'Library Images',
            },
        ),
    ]
