# Generated by Django 2.2 on 2020-05-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200515_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug_report',
            name='contact_no',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='contact_no',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='library',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
