# Generated by Django 2.2 on 2020-05-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_enquiry_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
