# Generated by Django 2.2 on 2020-05-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200520_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='ammenities',
        ),
        migrations.AddField(
            model_name='library',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='core.ammenities'),
        ),
    ]
