# Generated by Django 2.2 on 2020-05-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200521_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='max_price_range',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='min_price_range',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='no_of_seats',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='library',
            name='non_refundable_charges',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='views',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
