# Generated by Django 2.2 on 2020-05-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200521_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='library',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
